# // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# // SPDX-License-Identifier: MIT-0
apiVersion: v1
kind: Pod
spec:
 containers:
  - name: spark-kubernetes-executor
    env:
    - name: AWS_ROLE_ARN
      value: "arn:aws:iam::ACCOUNTA:role/emr-on-eks-client-a-role"
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"