site_name: "EMR Containers Best Practices Guides"
repo_name: "aws/aws-emr-containers-best-practices"
repo_url: "https://github.com/aws/aws-emr-containers-best-practices"
docs_dir: "content"
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Guides:
      - Introduction: 'index.md'
      - EMR on EKS(AWS Outposts): 'outposts/emr-containers-on-outposts.md'
  - Security:
      - Encryption: 'security/docs/spark/encryption.md'
      - Data Encryption: 'security/docs/spark/data-encryption.md'
      - Network Security: 'security/docs/spark/network-security.md'
      - Secrets: 'security/docs/spark/secrets.md'
      - Chain IAM Roles: 'security/docs/spark/chain-role.md'
  - Submit applications:
      - Pyspark: 'submit-applications/docs/spark/pyspark.md'
      - Build Multi-arch Docker Image: 'submit-applications/docs/spark/multi-arch-image.md'
  - Storage:
      - EBS: 'storage/docs/spark/ebs.md'
      - FSx for Lustre: 'storage/docs/spark/fsx-lustre.md'
      - Instance Store: 'storage/docs/spark/instance-store.md'
  - Metastore Integration:
      - Hive Metastore: 'metastore-integrations/docs/hive-metastore.md'
      - AWS Glue: 'metastore-integrations/docs/aws-glue.md'
  - Troubleshooting:
      - Spark Log Location in S3 and CloudWatch: 'troubleshooting/docs/where-to-look-for-spark-logs.md'
      - Change Log Level: 'troubleshooting/docs/change-log-level.md'
      - Connect to Spark UI: 'troubleshooting/docs/connect-spark-ui.md'
      - Connect to Spark UI via Reverse Proxy: 'troubleshooting/docs/reverse-proxy-sparkui.md'
      - Self Hosted SHS: 'troubleshooting/docs/self-hosted-shs.md'
      - RBAC Permissions error: 'troubleshooting/docs/rbac-permissions-errors.md'
      - EKS Cluster AutoScaler: 'troubleshooting/docs/eks-cluster-auto-scaler.md'
      - EKS Karpenter: 'troubleshooting/docs/karpenter.md'
  - Node Placement:
      - EKS Node placement: 'node-placement/docs/eks-node-placement.md'
      - EKS Fargate Node placement: 'node-placement/docs/fargate-node-placement.md'
  - Performance:
      - Dynamic Resource Allocation: 'performance/docs/dra.md'
      - BinPacking: 'performance/docs/binpack.md'
      - EKS Best Practices: 'best-practices-and-recommendations/eks-best-practices.md'
  - Cost Tracking and Optimization:
      - Cost Optimization using EC2 Spot Instances: 'cost-optimization/docs/cost-optimization.md'
      - Node Decommission: 'cost-optimization/docs/node-decommission.md'
      - Cost Tracking: 'cost-optimization/docs/cost-tracking.md'
  - Scalability:
      - Glossary and Terms: 'scalability/docs/scalaiblity-glossary.md'
      - Known Factors for Spark Operator: 'scalability/docs/known-factors-spark-operator.md'
      - Known Factors for StartJobRun API: 'scalability/docs/known-factors-start-job-run.md'
      - Recommendation for StartJobRun: 'scalability/docs/load-test-for-start-job-run-api.md'
      - Recommendation for Spark Operator: 'scalability/docs/load-test-for-spark-operator.md'
      - Grafana Dashboard: 'scalability/docs/graphana-dashboard.md'
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
