site_name: "EMR Containers Best Practices Guides"
repo_name: "aws/aws-emr-containers-best-practices"
repo_url: "https://github.com/aws/aws-emr-containers-best-practices"
docs_dir: "content"
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Guides:
      - Introduction: 'index.md'
      - EMR on EKS(AWS Outposts): 'outposts/emr-containers-on-outposts.md'
  - Security:
      - Encryption: 'security/docs/spark/encryption.md'
      - Data Encryption: 'security/docs/spark/data-encryption.md'
      - Secrets: 'security/docs/spark/secrets.md'
  - Submit applications:
      - Pyspark: 'submit-applications/docs/spark/pyspark.md'
  - Storage:
      - EBS: 'storage/docs/spark/ebs.md'
      - FSx for Lustre: 'storage/docs/spark/fsx-lustre.md'
  - Metastore Integration:
      - Hive Metastore: 'metastore-integrations/docs/hive-metastore.md'
      - AWS Glue: 'metastore-integrations/docs/aws-glue.md'
  - Debugging:
      - Change Log Level: 'debugging/docs/change-log-level.md'
      - Connect to Spark UI: 'debugging/docs/connect-spark-ui.md'
  - Troubleshoot:
      - PVC permission: 'troubleshoot/docs/pvc-permission.md'    
  - Node Placement:
      - EKS Node placement: 'node-placement/docs/eks-node-placement.md'
      - EKS Fargate Node placement: 'node-placement/docs/fargate-node-placement.md'
  - Performance:
      - Dynamic Resource Allocation: 'performance/docs/dra.md'
      - EKS Best Practices: 'best-practices-and-recommendations/eks-best-practices.md'
  - Spot instances resiliency:
      - Copying Shuffle data: 'spot-instances-resiliency/docs/copying-shuffle-data.md'
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
