{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-scheduler.serviceAccountName" . }}
  labels:
    {{- include "kube-scheduler.labels" . | nindent 4 }}
{{- end }}